import { Button, Container, Paper, Text } from "@mantine/core";
import { GithubIcon } from "@mantine/ds";
import { useRouter } from "next/router";
import useAppTheme from "../hooks/useAppTheme";
import Head from "next/head";
import { useUser } from "@supabase/auth-helpers-react";

export default function Home() {
  const { colors, isDark, textColor } = useAppTheme();
  const user = useUser();
  const router = useRouter();
  const getStartedPath = user ? "/room/list" : "/auth/signin";
  const handleGetStarted = () => router.push(getStartedPath);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container size={600} p={20}>
        <Paper component='section' shadow='xs' p='md' bg={isDark ? colors.gray[9] : "white"}>
          <Text sx={{ color: textColor }} component='h1' size={30}>
            Chat Line
          </Text>
          <Text component='p' sx={{ color: textColor }}>
            A LightWeight Simple ID based chat app made using Nextjs, Mantine UI, Supabase 🤯
          </Text>
          <Paper
            display='flex'
            bg={isDark ? colors.gray[9] : "white"}
            sx={{ justifyContent: "center", gap: "20px", margin: "1em 0em", flexWrap: "wrap" }}
          >
            <Button variant='gradient' onClick={handleGetStarted}>
              Get Started 🌟
            </Button>
            <Button variant='light'>
              <Text mr={6}>Github Repo</Text>
              <GithubIcon size={16} />
            </Button>
            <Button component='a' href='https://mmv-docs.vercel.app/' target='_blank' rel="noopener noreferrer" variant='light'>
              Documentation 📃
            </Button>
          </Paper>
        </Paper>
      </Container>
    </>
  );
}
