import { Button, Container, Paper, Skeleton } from "@mantine/core";
import Head from "next/head";
import { useEffect } from "react";
import useKanyeRest from "../hooks/useKanyeRest";

export default function Home() {
  const { data, error, isLoading, mutate } = useKanyeRest();

  useEffect(() => {
    mutate();
  }, [mutate]);

  if (error) return <h1>ERORRR</h1>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container size={600} p={20}>
        {isLoading ? (
          <Paper>
            <Skeleton height={8} radius='xl' />
            <Skeleton height={8} mt={6} radius='xl' />
            <Skeleton height={8} mt={6} width='70%' radius='xl' />
          </Paper>
        ) : (
          <>
            <p>{data}</p>
            <Button variant='filled' color={""} onClick={() => mutate()}>
              Get Kanye quote
            </Button>
          </>
        )}
      </Container>
    </>
  );
}
